/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EditorButton: typeof import('./src/components/TopologyEditor/EditorHeader/EditorButton.vue')['default']
    EditorCanvas: typeof import('./src/components/TopologyEditor/EditorCanvas/index.vue')['default']
    EditorContextMenu: typeof import('./src/components/TopologyEditor/EditorCanvas/EditorContextMenu.vue')['default']
    EditorHeader: typeof import('./src/components/TopologyEditor/EditorHeader/index.vue')['default']
    EditorIcon: typeof import('./src/components/TopologyEditor/EditorIcon/index.vue')['default']
    EditorProps: typeof import('./src/components/TopologyEditor/EditorProps/index.vue')['default']
    EditorPropsCanvas: typeof import('./src/components/TopologyEditor/EditorProps/EditorPropsCanvas.vue')['default']
    EditorPropsPen: typeof import('./src/components/TopologyEditor/EditorProps/EditorPropsPen.vue')['default']
    EditorPropsPenData: typeof import('./src/components/TopologyEditor/EditorProps/EditorPropsPenData.vue')['default']
    EditorPropsPenEvents: typeof import('./src/components/TopologyEditor/EditorProps/EditorPropsPenEvents.vue')['default']
    EditorPropsTabStructure: typeof import('./src/components/TopologyEditor/EditorProps/EditorPropsTabStructure.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTree: typeof import('element-plus/es')['ElTree']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopologyEditor: typeof import('./src/components/TopologyEditor/index.vue')['default']
  }
}
